---
name: Python Lint

on: push

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      # checkout repo under $GITHUB_WORKSPACE
      - name: Checkout action
        uses: actions/checkout@v2

      # install latest python version
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --exclude ./model

      - name: Lint with mypy
        run: |
          pip install mypy
          mypy --namespace-packages $(find . -name "*.py")

      - name: Lint with bandit
        run: |
          pip install bandit
          bandit $(find . -name "*.py")

      - name: Lint with pydocstyle
        run: |
          pip install pydocstyle
          pydocstyle --convention=google $(find . -name "*.py")

      - name: Reformat with black
        uses: psf/black@stable

      # you need all config files valid for this to work
      - name: Lint with yamllint
        run: |
          pip install yamllint
          yamllint $(find . -name "*.yaml")
